package typecalc

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/creator915/Koncept_OS/internal/graph"
)

// ProbePoint identifies a single insertion point for the probe-based fault
// localization (§3 plan_probes). Each intermediate attribute is a probe
// point — observe its value when running the integration test, then walk
// backwards along the refinement order to localize the fault.
type ProbePoint struct {
	Attribute string `json:"attribute"`
	Producer  string `json:"producer"`  // object id producing this attribute
	Consumers []string `json:"consumers"`
	// TopoIndex is the position of the producer in topological order.
	// Lower-indexed probes are upstream — observing them first lets you
	// short-circuit on early divergence.
	TopoIndex int `json:"topoIndex"`
}

// ProbePlanData is the structured payload of a KindProbePlan TypedValue.
// Matches §3 ProbePlan<AttrPath[]>.
type ProbePlanData struct {
	Points []ProbePoint `json:"points"`
}

// ProbePlanFromGraph generates a ProbePlan by topologically sorting the
// graph's objects (producer-before-consumer). Only intermediate attributes
// — those both produced and consumed within the graph — become probe
// points. Pure inputs (attributes consumed but never produced internally)
// and pure outputs (produced but never consumed) are skipped because
// observing them gives no localization information.
//
// The doc §3 says "ProbePlan is generated by the system from Graph (rule
// plan_probes), not the LLM — purely mechanical". This function is the
// implementation of that rule.
func ProbePlanFromGraph(g *graph.Graph) (*ProbePlanData, error) {
	if g == nil {
		return &ProbePlanData{}, nil
	}
	produces := map[string][]string{} // attribute → producer object ids
	consumes := map[string][]string{} // attribute → consumer object ids
	objIDs := make([]string, 0, len(g.Objects))
	for id, obj := range g.Objects {
		objIDs = append(objIDs, id)
		for _, attr := range obj.Produces {
			produces[attr] = append(produces[attr], id)
		}
		for _, attr := range obj.Consumes {
			consumes[attr] = append(consumes[attr], id)
		}
	}
	// Topological sort: producer before consumer. Build the obj→obj
	// edges via the produced/consumed attribute join.
	indeg := make(map[string]int, len(objIDs))
	successors := make(map[string][]string, len(objIDs))
	for _, prodID := range objIDs {
		prodObj := g.Objects[prodID]
		for _, attr := range prodObj.Produces {
			for _, consID := range consumes[attr] {
				if consID == prodID {
					continue
				}
				successors[prodID] = append(successors[prodID], consID)
				indeg[consID]++
			}
		}
	}
	// Kahn's algorithm. Stable sort entries to keep output deterministic.
	queue := []string{}
	for _, id := range objIDs {
		if indeg[id] == 0 {
			queue = append(queue, id)
		}
	}
	sort.Strings(queue)
	topoIndex := map[string]int{}
	order := 0
	for len(queue) > 0 {
		head := queue[0]
		queue = queue[1:]
		topoIndex[head] = order
		order++
		var nextRound []string
		for _, succ := range successors[head] {
			indeg[succ]--
			if indeg[succ] == 0 {
				nextRound = append(nextRound, succ)
			}
		}
		sort.Strings(nextRound)
		queue = append(queue, nextRound...)
	}
	// Cycle detection: any object without a topo index participates in a
	// cycle. Probe points for such objects are emitted at the end with
	// TopoIndex = -1 so the consumer can warn or skip them.
	for _, id := range objIDs {
		if _, ok := topoIndex[id]; !ok {
			topoIndex[id] = -1
		}
	}
	// Emit probe points for intermediate attributes.
	plan := &ProbePlanData{}
	for attr := range produces {
		cs := consumes[attr]
		if len(cs) == 0 {
			continue // not an intermediate
		}
		// One probe per attribute. If multiple producers exist (which
		// validation should already flag as an error), pick the
		// lowest-indexed producer; we still emit the rest as advisories.
		producers := produces[attr]
		sort.Slice(producers, func(i, j int) bool {
			return topoIndex[producers[i]] < topoIndex[producers[j]]
		})
		sort.Strings(cs)
		plan.Points = append(plan.Points, ProbePoint{
			Attribute: attr,
			Producer:  producers[0],
			Consumers: cs,
			TopoIndex: topoIndex[producers[0]],
		})
	}
	sort.Slice(plan.Points, func(i, j int) bool {
		if plan.Points[i].TopoIndex != plan.Points[j].TopoIndex {
			return plan.Points[i].TopoIndex < plan.Points[j].TopoIndex
		}
		return plan.Points[i].Attribute < plan.Points[j].Attribute
	})
	return plan, nil
}

// NewProbePlan wraps ProbePlanData into a TypedValue.
func NewProbePlan(d *ProbePlanData) *TypedValue {
	raw, _ := json.Marshal(d)
	return &TypedValue{Kind: KindProbePlan, Payload: string(raw)}
}

// DecodeProbePlan extracts ProbePlanData.
func DecodeProbePlan(tv *TypedValue) (*ProbePlanData, error) {
	if tv == nil || tv.Kind != KindProbePlan {
		return nil, fmt.Errorf("DecodeProbePlan: wrong kind (got %v)", tv)
	}
	var d ProbePlanData
	if err := json.Unmarshal([]byte(tv.Payload), &d); err != nil {
		return nil, fmt.Errorf("decode ProbePlanData: %w", err)
	}
	return &d, nil
}

// ProbeObservation is a single (probe-point, observed-value) record.
type ProbeObservation struct {
	Attribute string `json:"attribute"`
	Value     string `json:"value"`
	Note      string `json:"note,omitempty"`
}

// ProbeResultData is the structured payload of a KindProbeResult.
type ProbeResultData struct {
	Plan         []ProbePoint       `json:"plan"`
	Observations []ProbeObservation `json:"observations"`
}

// NewProbeResult wraps observations into a typed value.
func NewProbeResult(d *ProbeResultData) *TypedValue {
	raw, _ := json.Marshal(d)
	return &TypedValue{Kind: KindProbeResult, Payload: string(raw)}
}

// DecodeProbeResult extracts ProbeResultData.
func DecodeProbeResult(tv *TypedValue) (*ProbeResultData, error) {
	if tv == nil || tv.Kind != KindProbeResult {
		return nil, fmt.Errorf("DecodeProbeResult: wrong kind (got %v)", tv)
	}
	var d ProbeResultData
	if err := json.Unmarshal([]byte(tv.Payload), &d); err != nil {
		return nil, fmt.Errorf("decode ProbeResultData: %w", err)
	}
	return &d, nil
}

// FaultLocatedDetail is the structured payload of a KindFaultLocated.
// Matches §3 FaultLocated<ModuleId, AttrPath, Reason>.
type FaultLocatedDetail struct {
	ModuleID string `json:"moduleId"`
	AttrPath string `json:"attrPath"`
	Reason   string `json:"reason"`
}

// NewFaultLocated wraps a fault-localization verdict.
func NewFaultLocated(moduleID, attrPath, reason string) *TypedValue {
	d := FaultLocatedDetail{ModuleID: moduleID, AttrPath: attrPath, Reason: reason}
	raw, _ := json.Marshal(d)
	return &TypedValue{Kind: KindFaultLocated, Payload: string(raw)}
}

// LocateFaultFromObservations is the heuristic implementation of §3
// locate_fault used as a fallback when no LLM is available. It walks
// observations in topological order and returns the first attribute
// whose Note marks divergence. Use LocateFaultViaLLM for the strict
// LLM-actored implementation.
func LocateFaultFromObservations(g *graph.Graph, plan *ProbePlanData, obs *ProbeResultData) *TypedValue {
	if plan == nil || obs == nil {
		return NewFaultLocated("", "", "no plan or observations")
	}
	byAttr := map[string]ProbeObservation{}
	for _, o := range obs.Observations {
		byAttr[o.Attribute] = o
	}
	sort.Slice(plan.Points, func(i, j int) bool {
		return plan.Points[i].TopoIndex < plan.Points[j].TopoIndex
	})
	for _, p := range plan.Points {
		o, ok := byAttr[p.Attribute]
		if !ok {
			continue
		}
		if o.Note == "" {
			continue
		}
		return NewFaultLocated(p.Producer, p.Attribute, o.Note)
	}
	return NewFaultLocated("", "", "no observation flagged divergence")
}

// LocateFaultViaLLM is the strict §3 implementation of locate_fault: actor
// is ActorLLM. It assembles the inputs (descriptions of every probe
// point's producer + signatures + observed values) and asks the LLM to
// pick the offending module. The agent is told to walk the partial order
// from output backwards to the first attribute whose value diverges.
//
// If env or env.LLMInvoker is nil, falls back to LocateFaultFromObservations
// — keeping callers without LLM access (unit tests, headless tools)
// functional, while still giving them strict mode when an invoker is
// supplied.
func LocateFaultViaLLM(ctx context.Context, env *RuleEnv, g *graph.Graph,
	descriptions map[string]string, signatures map[string]string,
	plan *ProbePlanData, obs *ProbeResultData,
) (*TypedValue, error) {
	if env == nil || env.LLMInvoker == nil {
		return LocateFaultFromObservations(g, plan, obs), nil
	}
	if plan == nil || obs == nil {
		return NewFaultLocated("", "", "no plan or observations"), nil
	}
	expected := SumType{
		{Kind: KindFaultLocated},
		{Kind: KindCannotReproduce},
	}
	prompt := buildLocateFaultPrompt(plan, obs, descriptions, signatures)
	raw, err := env.LLMInvoker(ctx, env, prompt, expected)
	if err != nil {
		return nil, fmt.Errorf("LLM invoker for locate_fault: %w", err)
	}
	out, err := ParseLLMOutput(raw, expected)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// buildLocateFaultPrompt formats a structured prompt for the locate_fault
// LLM invocation. The form is parameterized so the same prompt builder
// powers both the strict actor=LLM path and the unit-test stub paths
// (which can compare prompt structure across implementations).
func buildLocateFaultPrompt(plan *ProbePlanData, obs *ProbeResultData,
	descriptions map[string]string, signatures map[string]string,
) string {
	var b strings.Builder
	b.WriteString("Rule: locate_fault\n")
	b.WriteString("Inputs: ProbeResult observations + module descriptions/signatures.\n")
	b.WriteString("Walk attribute paths in topological order. From the LAST observation\n")
	b.WriteString("backwards to the FIRST that diverges from expectation, identify the\n")
	b.WriteString("attribute whose value first goes wrong — its producer is the fault.\n\n")
	b.WriteString("Output format:\n")
	b.WriteString("  TYPE: FaultLocated\n  {\"moduleId\":\"...\",\"attrPath\":\"...\",\"reason\":\"...\"}\n")
	b.WriteString("Or, if no clean attribution is possible:\n")
	b.WriteString("  TYPE: CannotReproduce\n  {\"reason\":\"...\"}\n\n")
	b.WriteString("Probe points (topological order):\n")
	sort.Slice(plan.Points, func(i, j int) bool {
		return plan.Points[i].TopoIndex < plan.Points[j].TopoIndex
	})
	for _, p := range plan.Points {
		fmt.Fprintf(&b, "  [%d] attribute=%q producer=%q consumers=%v\n",
			p.TopoIndex, p.Attribute, p.Producer, p.Consumers)
		if d := descriptions[p.Producer]; d != "" {
			fmt.Fprintf(&b, "      description: %s\n", trim(d, 200))
		}
		if s := signatures[p.Producer]; s != "" {
			fmt.Fprintf(&b, "      signature:   %s\n", trim(s, 200))
		}
	}
	b.WriteString("\nObservations:\n")
	for _, o := range obs.Observations {
		note := o.Note
		if note == "" {
			note = "(no divergence flagged)"
		}
		fmt.Fprintf(&b, "  attribute=%q value=%s note=%q\n", o.Attribute, trim(o.Value, 80), note)
	}
	return b.String()
}
