package router

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
)

// Feedback loop — the heart of the v9.0 type-driven design.
//
// In a ReAct agent, when a test fails the LLM "thinks" about what to do
// next: maybe re-read the file, maybe edit a different module, maybe ask
// for clarification. The agent loop has to babysit this — every error
// becomes a free-form decision the LLM has to navigate without strong
// guarantees. v8.x kcpos accumulated 9 hooks trying to constrain this
// freedom.
//
// In v9.0's type-driven design, the LLM never makes that decision. Errors
// are typed values (CompileError, TestError, ReviewFailed, …). A
// SYSTEM-level enrichment handler converts each error type into a
// Request<Task, …context…> that already contains:
//
//   - the original task description (so the LLM doesn't need to "remember")
//   - the specific error data (ErrorCode, ErrorLog, failing test case,
//     reviewer reasons, …) extracted into named fields
//   - explicit guidance phrased as imperatives ("re-emit Uncompiled<…> with
//     the function returning the expected shape" — derived from the error
//     structure, not generated by the LLM)
//
// The LLM then handles Request<…> with a focused prompt: "here's a task
// you were doing, here's exactly what went wrong, here's exactly what
// to produce next. Pick branch A (retry with this code) or B (escalate
// as Obstacle because the issue is structural)."
//
// The agent never sees CompileError directly. The Router intercepts and
// passes through enrichment first. From the LLM's standpoint, "what to
// do next" is a one-step branch pick inside a known sum type.
//
// This file supplies the canonical Request type + the enrichment-handler
// helpers that wrap raw error types into them.

// Request is the enriched-feedback envelope. It carries:
//
//   - Task: the immutable original instruction the LLM was given (so it
//     doesn't drift after several retry rounds)
//   - Context: a map of named field → value blobs (ErrorCode, ErrorLog,
//     failingTestCase, reviewerReasons, …). Schema-light by design;
//     the prompt builder picks fields it cares about.
//   - Guidance: imperatives like "produce a Uncompiled<Lang<Go,Code>>
//     with main() returning *Foo not Foo". Derived structurally from
//     the error type by the enrichment handler.
//   - Attempts: how many enrich-then-retry rounds preceded this. Used
//     by CycleCap-style throttles to avoid infinite repair loops.
//
// Request lives in router/ rather than typecalc/ because it's a
// fundamental control-flow construct, not specific to one verification
// step. Every error-recovery loop in v9.0 funnels through this shape.
type Request struct {
	Task     string            `json:"task"`
	Context  map[string]string `json:"context,omitempty"`
	Guidance []string          `json:"guidance,omitempty"`
	Attempts int               `json:"attempts"`
}

// Enricher turns a raw error TypedValue into an enriched Request<...>.
// Each error type registers its own Enricher; the Router doesn't
// special-case any of them.
//
// Implementations should:
//   1. Unmarshal in.Content into the error-specific shape
//      (e.g. type CompileErrorPayload { Task, ErrorCode, ErrorLog string }).
//   2. Build a Request whose Task carries the original instruction,
//      Context carries the error fields, and Guidance contains 1-3
//      imperatives the next LLM step can act on directly.
//   3. Return a TypedValue tagged with the Request-flavored output type
//      ("Request<Compile>", "Request<Test>", "Request<Review>", …) so
//      the next handler is a focused retry-LLM step.
type Enricher interface {
	Handler // Enricher IS a Handler. The router doesn't distinguish.
}

// EnrichHandler is the function-shaped Enricher adapter. Most error
// types only need a small struct unmarshal + Request build, so this
// keeps the boilerplate minimal.
type EnrichHandler struct {
	In       string // input error type tag (e.g. "CompileError")
	Out      string // output type tag (e.g. "Request<Compile>")
	Transform func(in TypedValue) (Request, error)
}

func (e *EnrichHandler) Accepts() string { return e.In }
func (e *EnrichHandler) Outputs() []string { return []string{e.Out} }

func (e *EnrichHandler) Handle(ctx context.Context, in TypedValue) (TypedValue, error) {
	req, err := e.Transform(in)
	if err != nil {
		return TypedValue{}, fmt.Errorf("enrich %q: %w", e.In, err)
	}
	out, err := NewTypedValue(e.Out, req)
	if err != nil {
		return TypedValue{}, err
	}
	out.Channel = in.Channel
	out.Lang = in.Lang
	return out, nil
}

// RetryAttemptsMeta is the conventional Meta key for accumulating
// per-object retry counts across enrich+retry cycles. Handlers update
// it; CycleCap-style limits read it.
const RetryAttemptsMeta = "router.retry_attempts"

// IncrementRetry returns the next-iteration value of TypedValue.Meta
// with the retry counter bumped. Pure (input unmodified).
func IncrementRetry(meta map[string]string) map[string]string {
	out := map[string]string{}
	for k, v := range meta {
		out[k] = v
	}
	n := 0
	if s, ok := meta[RetryAttemptsMeta]; ok {
		fmt.Sscanf(s, "%d", &n)
	}
	out[RetryAttemptsMeta] = fmt.Sprintf("%d", n+1)
	return out
}

// FormatRequestForLLM renders a Request as the LLM-facing prompt body.
// Used by retry-LLM handlers (typically registered for "Request<…>"
// input type). The format is intentionally rigid so the LLM doesn't
// have to "find" the relevant data; it's all in well-known sections.
//
//	## Original task
//	<Task>
//
//	## What went wrong (attempt N)
//	<Context entries as ### field-name + content>
//
//	## What to produce next
//	<Guidance bullets>
//
//	Reply with: TYPE: <one of allowed branches>\n<payload>
func FormatRequestForLLM(req Request, allowedBranches []string) string {
	var b strings.Builder
	b.WriteString("## Original task\n")
	b.WriteString(req.Task)
	b.WriteString("\n\n")

	fmt.Fprintf(&b, "## What went wrong (attempt %d)\n", req.Attempts)
	if len(req.Context) == 0 {
		b.WriteString("(no specific context — likely a router infrastructure error; pick the Obstacle branch)\n\n")
	} else {
		// Stable key order so prompts are reproducible.
		keys := make([]string, 0, len(req.Context))
		for k := range req.Context {
			keys = append(keys, k)
		}
		// Cheap sort — small N, no need for sort.Strings dep on this file.
		for i := 1; i < len(keys); i++ {
			for j := i; j > 0 && keys[j-1] > keys[j]; j-- {
				keys[j-1], keys[j] = keys[j], keys[j-1]
			}
		}
		for _, k := range keys {
			fmt.Fprintf(&b, "### %s\n%s\n\n", k, req.Context[k])
		}
	}

	b.WriteString("## What to produce next\n")
	if len(req.Guidance) == 0 {
		b.WriteString("(none — judge from the context above)\n")
	} else {
		for _, g := range req.Guidance {
			fmt.Fprintf(&b, "- %s\n", g)
		}
	}
	b.WriteString("\n")

	fmt.Fprintf(&b, "## Reply format\nReply with one of these branch tags on the first line:\n")
	for _, br := range allowedBranches {
		fmt.Fprintf(&b, "  TYPE: %s\n", br)
	}
	b.WriteString("Then the typed payload (typically JSON).\n")
	return b.String()
}

// MustMarshal is a small helper for tests + Enricher implementations
// that want to embed structured data in Request.Context as a
// JSON-string field.
func MustMarshal(v interface{}) string {
	raw, err := json.Marshal(v)
	if err != nil {
		return fmt.Sprintf("(unmarshalable: %v)", err)
	}
	return string(raw)
}
